# action.yml
name: 'Tanzu Deploy'
description: 'Deploy an application to Tanzu Platform for Kubernetes'
inputs:
  tanzu_api_token:
    description: 'API Token used to authenticate to Tanzu Platform'
    required: true
    default: ''
  container_repository:
    description: 'Container image repository (e.g. myrepo.azurecr.io)'
    required: true
    default: 'docker.io'
  container_repository_username:
    description: 'Username for image repository'
    required: true
    default: ''
  container_repository_password:
    description: 'Password for image repository'
    required: true
    default: 'docker.io'
  container_registry:
    description: 'Registry you will push images to (e.g. myrepo.azurecr.io/build/{name}'
    required: true
    default: ''
  project:
    description: 'Tanzu Platform project'
    required: true
    default: ''
  space:
    description: 'Tanzu Platform space'
    required: true
    default: ''

outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.tanzu_api_token }}
    - ${{ inputs.container_repository }}
    - ${{ inputs.container_repository_username }}
    - ${{ inputs.container_repository_password }}
    - ${{ inputs.container_registry }}
    - ${{ inputs.project }}
    - ${{ inputs.space }}

