name: tanzu-deploy-workflow
on: [push]
jobs:
  tanzu_deploy_job:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Deploy to Tanzu Platform on Commit
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy application to Tanzu Platform
        uses: cpage-pivotal/tanzu-deploy-action@v1.4-app-advisor
        with:
          tanzu_api_token: ${{ secrets.TanzuApiToken }}
          container_registry: ghcr.io/${{ github.actor }}/<<ENTER VALUE>>
          buildPlanSource: simple.tanzu.vmware.com
          javaVersion: 17
          project: <<ENTER VALUE>>
          space: <<ENTER VALUE>>
          artifactory_token: ${{ secrets.ArtifactoryToken }}
          app_advisor_server: <<ENTER VALUE>>