name: tanzu-deploy-workflow
on: [push]
jobs:
  tanzu_deploy_job:
    runs-on: ubuntu-latest
    name: Deploy to Tanzu Platform on Commit
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: <<ENTER VALUE>>
          username: ${{ secrets.RepositoryUsername }}
          password: ${{ secrets.RepositoryPassword }}
      - name: Deploy application to Tanzu Platform
        uses: cpage-pivotal/tanzu-deploy-action@v1.3
        with:
          tanzu_api_token: ${{ secrets.TanzuApiToken }}
          container_registry: <<ENTER VALUE>>
          project: <<ENTER VALUE>>
          space: <<ENTER VALUE>>
